# Generated by Django 5.1.15 on 2026-05-26 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0003_initial'),
        ('review', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyflag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='emissions.activityrecord'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='review_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='review.reviewitem'),
        ),
    ]
