# Generated by Django 5.1.15 on 2026-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyflag',
            name='kind',
            field=models.CharField(choices=[('outlier', 'Statistical outlier vs history'), ('missing_factor', 'No emission factor matched'), ('unmapped_code', 'Plant/airport code not in lookup'), ('duplicate', 'Possible duplicate of existing record'), ('unit_guess', 'Unit was inferred, not explicit'), ('invalid_value', 'Negative or zero quantity'), ('implausible', 'Physically implausible (distance/period)')], max_length=32),
        ),
    ]
