# Generated by Django 5.1.15 on 2026-05-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('site_name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_category', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 (direct)'), ('2', 'Scope 2 (purchased energy)'), ('3', 'Scope 3 (value chain)')], max_length=1)),
                ('unit', models.CharField(max_length=16)),
                ('co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('valid_year', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('activity_category', 'region', 'valid_year', 'source')},
            },
        ),
    ]
