# Generated by Django 5.1.15 on 2026-05-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='plantcode',
            unique_together={('organization', 'code')},
        ),
    ]
