# Generated by Django 5.1.15 on 2026-05-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_category', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 (direct)'), ('2', 'Scope 2 (purchased energy)'), ('3', 'Scope 3 (value chain)')], max_length=1)),
                ('site_code', models.CharField(blank=True, max_length=32)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(max_length=16)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_edited', models.BooleanField(default=False)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
        ),
    ]
