# Generated by Django 5.1.15 on 2026-05-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityrecord',
            options={'ordering': ['-created_at']},
        ),
    ]
