r"""Analyst review & sign-off workflow.

Review state is modeled separately from the ActivityRecord itself so the
canonical data stays clean and the workflow can evolve independently. The
lifecycle the assignment asks for:

    pending -> (flagged?) -> approved -> locked
                         \-> rejected

'locked' is the audit-final state: once locked, the underlying
ActivityRecord must not change (enforced in the view/permission layer).
AnomalyFlags are what makes "what looks suspicious" visible — generated by
the anomaly service at ingest and resolvable by an analyst.
"""
from django.conf import settings
from django.db import models

from apps.common.models import TenantScopedModel


class ReviewItem(TenantScopedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending review"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"
        LOCKED = "locked", "Locked for audit"

    activity = models.OneToOneField(
        "emissions.ActivityRecord", on_delete=models.CASCADE, related_name="review"
    )
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="+"
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    comment = models.TextField(blank=True)


class AnomalyFlag(TenantScopedModel):
    """A reason a row 'looks suspicious'. Several can attach to one item."""

    class Kind(models.TextChoices):
        OUTLIER = "outlier", "Statistical outlier vs history"
        MISSING_FACTOR = "missing_factor", "No emission factor matched"
        UNMAPPED_CODE = "unmapped_code", "Plant/airport code not in lookup"
        DUPLICATE = "duplicate", "Possible duplicate of existing record"
        UNIT_GUESS = "unit_guess", "Unit was inferred, not explicit"
        INVALID_VALUE = "invalid_value", "Negative or zero quantity"
        IMPLAUSIBLE = "implausible", "Physically implausible (distance/period)"

    review_item = models.ForeignKey(ReviewItem, on_delete=models.CASCADE, related_name="flags")
    kind = models.CharField(max_length=32, choices=Kind.choices)
    detail = models.TextField(blank=True)
    resolved = models.BooleanField(default=False)
