# Generated by Django 5.1.15 on 2026-05-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceconnection',
            options={'ordering': ['name']},
        ),
    ]
