# Generated by Django 5.1.15 on 2026-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_sourceconnection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='ingestion/%Y/%m/'),
        ),
    ]
