# Generated by Django 5.1.15 on 2026-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_ingestionbatch_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
